railstutorial_url: https://www.railstutorial.org/
michaelhartl_url: https://www.michaelhartl.com/
ror_tutorial_help_url: https://www.railstutorial.org/help
ror_sample_app_help_url: https://github.com/mhartl/sample_app_6th_ed
ror_contact_url: https://www.railstutorial.org/contact
learnenough_url: https://www.learnenough.com/
ror_tutorial_book_url: https://www.railstutorial.org/book
ror_tutorial_screencast_url: https://screencasts.railstutorial.org/
ror_url: https://rubyonrails.org/
ror_tutorial_news_url: https://news.railstutorial.org/

regex:
  email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
length:
  username_max_len: 50
  email_max_len: 256
  password_min_len: 6

gravatar:
  base_url: https://secure.gravatar.com/avatar
  default_size: 80
