railstutorial_url: https://www.railstutorial.org/
michaelhartl_url: https://www.michaelhartl.com/
ror_tutorial_help_url: https://www.railstutorial.org/help
ror_sample_app_help_url: https://github.com/mhartl/sample_app_6th_ed
ror_contact_url: https://www.railstutorial.org/contact
learnenough_url: https://www.learnenough.com/
ror_tutorial_book_url: https://www.railstutorial.org/book
ror_tutorial_screencast_url: https://screencasts.railstutorial.org/
ror_url: https://rubyonrails.org/
ror_tutorial_news_url: https://news.railstutorial.org/
